In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
#fever par simpleimputer , gender and city par ohe and cough par ordinal encoding

In [8]:
xtr,xts,ytr,yts=train_test_split(df.drop(columns=['has_covid']) , df['has_covid'],test_size=0.2)

# Without using column transformer

In [17]:
si=SimpleImputer()
xtr_fever=si.fit_transform(xtr[['fever']])  # Double brackets keep it 2D; sklearn requires 2D input.
xts_fever=si.transform(xts[['fever']])

In [18]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])
xtr_cough=oe.fit_transform(xtr[['cough']])
xts_cough=oe.transform(xts[['cough']])

In [35]:
ohe=OneHotEncoder(drop='first',sparse_output=False)
xtr_gender_city=ohe.fit_transform(xtr[['gender','city']])
xts_gender_city=ohe.transform(xts[['gender','city']])

In [36]:
xtr_gender_city

array([[0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [52]:
xtr_age=xtr[['age']].values  #values=It converts a DataFrame (or Series) into a NumPy array.
xts_age=xts[['age']].values

In [54]:
xtr_transformed=np.concatenate((xtr_age,xtr_fever,xtr_gender_city,xtr_cough),axis=1)
xts_transformed=np.concatenate((xts_age,xts_fever,xts_gender_city,xts_cough),axis=1)

# now using column transformer

In [57]:
from sklearn.compose import ColumnTransformer

In [58]:
trans=ColumnTransformer(transformers=[
    ('tnf1' , SimpleImputer() , ['fever']),
    ('tnf2' , OrdinalEncoder(categories=[['Mild','Strong']]) , ['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
] , remainder='passthrough'
)

In [61]:
trans.fit_transform(xtr)

array([[101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [ 98.,   1.,   1.,   0.,   0.,   1.,  23.],
       [101.,   0.,   0.,   0.,   0.,   0.,  84.],
       [ 98.,   0.,   1.,   0.,   0.,   0.,  73.],
       [101.,   0.,   0.,   1.,   0.,   0.,  49.],
       [101.,   1.,   0.,   0.,   0.,   1.,  34.],
       [101.,   0.,   0.,   1.,   0.,   0.,  64.],
       [101.,   0.,   0.,   0.,   1.,   0.,   8.],
       [104.,   0.,   1.,   0.,   0.,   0.,  51.],
       [101.,   0.,   1.,   1.,   0.,   0.,  15.],
       [102.,   1.,   0.,   0.,   0.,   0.,  24.],
       [100.,   1.,   0.,   0.,   0.,   0.,  47.],
       [104.,   0.,   1.,   0.,   0.,   1.,  44.],
       [101.,   0.,   1.,   0.,   1.,   0.,  82.],
       [103.,   0.,   1.,   0.,   1.,   0.,  60.],
       [101.,   1.,   1.,   0.,   0.,   0.,  47.],
       [101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [101.,   0.,   0.,   1.,   0.,   0.,  75.],
       [ 98.,   0.,   1.,   0.,   1.,   0.,  24.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [101.,   0.,   0.,   0.,   0.,   0.,  38.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,   5.],
       [ 98.,   0.,   0.,   0.,   0.,   1.,  65.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [102.,   0.,   1.,   0.,   0.,   1.,  74.],
       [ 99.,   1.,   1.,   0.,   0.,   0.,  66.],
       [100.,   0.,   1.,   0.,   1.,   0.,  55.],
       [102.,   0.,   0.,   1.,   0.,   0.,  49.],
       [ 99.,   1.,   0.,   1.,   0.,   0.,  59.],
       [101.,   0.,   0.,   0.,   0.,   1.,  19.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  72.],
       [100.,   1.,   0.,   0.,   0.,   0.,  19.],
       [102.,   0.,   1.,   0.,   1.,   0.,   5.],
       [102.,   1.,   0.,   1.,   0.,   0.,  33.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  10.],
       [103.,   0.,   0.,   0.,   1.,   0.,  69.],
       [100.,   0.,   1.,   0.,   0.,   0.,  80.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  14.],
       [102.,   1.,   0.,   0.,   1.,   0.,  82.],
       [103.,   1.,   1.,   0.,   0.,   0.,  46.],
       [101.,   1.,   1.,   0.,   1.,   0.,  79.],
       [101.,   0.,   0.,   0.,   0.,   0.,  20.],
       [103.,   1.,   1.,   0.,   1.,   0.,  70.],
       [104.,   0.,   0.,   0.,   0.,   0.,  12.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [ 98.,   1.,   0.,   1.,   0.,   0.,  40.],
       [101.,   1.,   0.,   0.,   0.,   0.,  42.],
       [101.,   1.,   0.,   1.,   0.,   0.,  34.],
       [101.,   1.,   1.,   0.,   0.,   0.,  14.],
       [104.,   0.,   0.,   0.,   0.,   0.,  18.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  31.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  69.],
       [102.,   1.,   0.,   0.,   0.,   0.,  82.],
       [101.,   0.,   1.,   1.,   0.,   0.,  38.],
       [104.,   0.,   1.,   0.,   1.,   0.,  16.],
       [101.,   0.,   1.,   1.,   0.,   0.,  19.],
       [103.,   0.,   0.,   0.,   1.,   0.,  48.],
       [104.,   0.,   1.,   0.,   1.,   0.,  51.],
       [100.,   1.,   0.,   0.,   1.,   0.,  13.],
       [101.,   0.,   1.,   1.,   0.,   0.,  42.],
       [ 98.,   1.,   1.,   0.,   0.,   0.,  12.],
       [103.,   0.,   0.,   0.,   0.,   0.,  16.],
       [103.,   0.,   1.,   0.,   1.,   0.,  83.],
       [102.,   0.,   1.,   0.,   0.,   0.,  64.],
       [102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [101.,   1.,   1.,   0.,   1.,   0.,  71.],
       [100.,   0.,   1.,   0.,   1.,   0.,  27.],
       [ 99.,   1.,   0.,   0.,   0.,   0.,  49.],
       [100.,   0.,   1.,   0.,   0.,   0.,  11.],
       [104.,   0.,   1.,   0.,   0.,   1.,  42.],
       [104.,   0.,   0.,   0.,   1.,   0.,   6.],
       [104.,   0.,   1.,   0.,   0.,   0.,  25.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  60.],
       [100.,   0.,   1.,   0.,   0.,   0.,  10.],
       [ 99.,   1.,   0.,   0.,   1.,   0.,  25.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  81.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  65.],
       [104.,   0.,   0.,   0.,   1.,   0.,  17.],
       [101.,   0.,   0.,   0.,   0.,   1.,  65.],
       [104.,   1.,   0.,   0.,   0.,   0.,  56.]])

In [62]:
trans.transform(xts)

array([[101.,   0.,   1.,   0.,   0.,   1.,  23.],
       [ 98.,   1.,   1.,   0.,   1.,   0.,  34.],
       [ 99.,   0.,   1.,   1.,   0.,   0.,  65.],
       [100.,   0.,   0.,   0.,   1.,   0.,   5.],
       [100.,   0.,   0.,   0.,   1.,   0.,  19.],
       [104.,   1.,   0.,   0.,   1.,   0.,  54.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  26.],
       [104.,   1.,   0.,   1.,   0.,   0.,  75.],
       [103.,   0.,   0.,   0.,   1.,   0.,  50.],
       [ 98.,   0.,   0.,   1.,   0.,   0.,  80.],
       [ 99.,   0.,   0.,   0.,   0.,   0.,  22.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  71.],
       [ 98.,   0.,   0.,   0.,   0.,   0.,  64.],
       [100.,   1.,   0.,   0.,   1.,   0.,  11.],
       [102.,   1.,   1.,   1.,   0.,   0.,  20.],
       [101.,   1.,   0.,   1.,   0.,   0.,  68.],
       [101.,   1.,   0.,   0.,   0.,   1.,  20.],
       [ 98.,   0.,   1.,   1.,   0.,   0.,  83.],
       [104.,   1.,   0.,   1.,   0.,   0.,  34.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.]])